---
name: Module-Build-Tiny
version: 0.006
author:
  - 'David Golden <dagolden@cpan.org>'
  - 'Leon Timmermans <leont@cpan.org>'
abstract: 'A tiny Build.PL compatible module builder'
license: perl
resources:
  bugtracker: http://github.com/Leont/module-build-tiny/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/Leont/module-build-tiny/tree
requires:
  perl: 5.006
  CPAN::Meta: 0
  ExtUtils::BuildRC: 0
  ExtUtils::Helpers: 0
no_index:
  directory:
    - t
generated_by: Leon Timmermans
dynamic_config: 0
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
keywords:
  - module
  - building
  - tiny
